### ISSUE TITLE
Series encoding lost from charm store URL for some charms

### ISSUE THREAD

**Issue by gnuoy** [juju-solutions/libcharmstore#2]
The OpenStack amulet tests started failing recently. On inspection this appeared to be due to charms being deployed with the wrong series. This seems to be due to a recent commit that removed the api URL from calls to theblues. Previously theblues was called with an api url pointing at the cs v4 endpoint. Below is an example of the change of behaviour:

> pip freeze | grep libcharm
libcharmstore==0.0.3

> ./bin/python2.7 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import charmstore
>>> bob = charmstore.Charm('cs:~openstack-charmers-next/trusty/percona-cluster')
>>> print(bob.id)
~openstack-charmers-next/trusty/percona-cluster-233
>>> 

> pip freeze | grep libcharm
libcharmstore==0.0.4

> ./bin/python2.7 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import charmstore
>>> bob = charmstore.Charm('cs:~openstack-charmers-next/trusty/percona-cluster')
>>> print(bob.id)
~openstack-charmers-next/percona-cluster-233
>>>

**Comment by ryan-beisner** [comment]
For reference, linking the juju-deployer bug:  https://bugs.launchpad.net/juju-deployer/+bug/1643027
